# just to make PodWeaver happy at the moment
package Data::Sah::Manual::Function;

=pod

=head1 NAME

Sah::Manual::Function - Creating a new function

=head1 INTRODUCTION

TODO

In this example we will be adding a function module called 'GenPass' which
contain two password generating functions: 'gen_simple_pass' and 'gen_pass'.

First create Data::SahFunc::GenPass distribution.

In Sah/Func/GenPass.pm, add something like this:

 package Data::Sah::Func::GenPass;
 use Data::SahUtils;
 use Any::Moose qw(:Role);
 ...
 func gen_simple_pass => sub {
     aliases => [],
     args => ...,
     ...
 };

 func gen_pass => sub {
     aliases => [],
     args => ...,
     ...
 };

In Sah/Compiler/perl/Func/GenPass.pm:

 ...

In Sah/Compiler/js/Func/GenPass.pm:

 ...

=cut
