# just to make PodWeaver happy at the moment
package Data::Schema::Manual::ExtendingType;

=pod

=head1 NAME

Data::Schema::Manual::ExtendingType - Extending an existing type

=head1 DESCRIPTION

THIS IS A STUB

Aside from creating a new type, you can also extend an existing type, which might
be easier. For example you can add a new attribute.

In this example, we will be adding 'is_palindrome' attribute to the 'str' type.

Steps:

* Create a distribution Data::Schema::TypeX::$STR::$SOMENAME.
Data::Schema::TypeX::Str::Palindrome.

* in Data::Schema::Emitter::Perl::Type::Str, add a method attr_is_palindrome:

XXX

* in Data::Schema::Emitter::Human::Type::Str add a method attr_is_palindrome:

XXX

* add appropriately for the other emitter you might care about (e.g. JavaScript).

=cut
